# Generated by Django 2.1.4 on 2018-12-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imagePath', models.CharField(max_length=200)),
                ('rollno', models.CharField(max_length=10)),
                ('presentCount', models.IntegerField(default=0)),
                ('absentCount', models.IntegerField(default=0)),
                ('awakeCount', models.IntegerField(default=0)),
            ],
        ),
    ]
