from django.db import models

class Call(models.Model):
    call_choices = ('ABSENT', 'PRESENT')
    created_on = models.DateTimeField(primary_key=True,auto_now_add=True)
    rollno =  models.CharField(max_length=10)
    status = models.CharField(max_length=200, default='ABSENT')
    prevCall = models.ForeignKey('self',null=True,on_delete=models.CASCADE)

# Create your models here
class StudentInfo(models.Model):
    CURRENT = ( ('ABSENT', 'Not in class'),
                ('CORRECT', 'Correct'),
                ('WRONG', 'Wrong'))
    name=models.CharField(max_length=100)
    imagePath = models.CharField(max_length=200)
    rollno =  models.CharField(primary_key=True,max_length=10)
    username =  models.CharField(max_length=10,null=True)
    presentCount=models.IntegerField(default=0)
    absentCount = models.IntegerField(default=0)
    awakeCount=models.IntegerField(default=0)
    curr_status = models.CharField(verbose_name='Current status', choices=CURRENT, default='ABSENT', max_length=20 )
    calls=models.ForeignKey(Call,null=True,on_delete=models.CASCADE)

class Question(models.Model):
    q=models.CharField(verbose_name="Question", max_length=1000)
    op1 = models.CharField(verbose_name="Option 1",max_length=500,null=True,blank=True)
    ans1 = models.BooleanField(verbose_name="Option 1 value", default=False)
    op2 = models.CharField(verbose_name="Option 2",max_length=500,null=True,blank=True)
    ans2 = models.BooleanField(verbose_name="Option 2 value", default=False)
    op3 = models.CharField(verbose_name="Option 3",max_length=500,null=True,blank=True)
    ans3 = models.BooleanField(verbose_name="Option 3 value", default=False)
    op4 = models.CharField(verbose_name="Option 4",max_length=500,null=True,blank=True)
    ans4 = models.BooleanField(verbose_name="Option 4 value", default=False)
    op5 = models.CharField(verbose_name="Option 5",max_length=500,null=True,blank=True)
    ans5 = models.BooleanField(verbose_name="Option 5 value", default=False)
    op6 = models.CharField(verbose_name="Option 6",max_length=500,null=True,blank=True)
    ans6 = models.BooleanField(verbose_name="Option 6 value", default=False)
    op7 = models.CharField(verbose_name="Option 7",max_length=500,null=True,blank=True)
    ans7 = models.BooleanField(verbose_name="Option 7 value", default=False)
    op8 = models.CharField(verbose_name="Option 8",max_length=500,null=True,blank=True)
    ans8 = models.BooleanField(verbose_name="Option 8 value", default=False)
    op9 = models.CharField(verbose_name="Option 9",max_length=500,null=True,blank=True)
    ans9 = models.BooleanField(verbose_name="Option 9 value", default=False)
    op10 = models.CharField(verbose_name="Option 10",max_length=500,null=True,blank=True)
    ans10 = models.BooleanField(verbose_name="Option 10 value", default=False)
    op11 = models.CharField(verbose_name="Option 11",max_length=500,null=True,blank=True)
    ans11 = models.BooleanField(verbose_name="Option 11 value", default=False)
    op12 = models.CharField(verbose_name="Option 12",max_length=500,null=True,blank=True)
    ans12 = models.BooleanField(verbose_name="Option 12 value", default=False)
    op13 = models.CharField(verbose_name="Option 13",max_length=500,null=True,blank=True)
    ans13 = models.BooleanField(verbose_name="Option 13 value", default=False)
    op14 = models.CharField(verbose_name="Option 14",max_length=500,null=True,blank=True)
    ans14 = models.BooleanField(verbose_name="Option 14 value", default=False)
    op15 = models.CharField(verbose_name="Option 15",max_length=500,null=True,blank=True)
    ans15 = models.BooleanField(verbose_name="Option 15 value", default=False)
    op16 = models.CharField(verbose_name="Option 16",max_length=500,null=True,blank=True)
    ans16 = models.BooleanField(verbose_name="Option 16 value", default=False)
    op17  = models.CharField(verbose_name="Option 17",max_length=500,null=True,blank=True)
    ans17 = models.BooleanField(verbose_name="Option 17 value", default=False)
    op18 = models.CharField(verbose_name="Option 18",max_length=500,null=True,blank=True)
    ans18 = models.BooleanField(verbose_name="Option 18 value", default=False)
    op19 = models.CharField(verbose_name="Option 19",max_length=500,null=True,blank=True)
    ans19 = models.BooleanField(verbose_name="Option 19 value", default=False)
    op20 = models.CharField(verbose_name="Option 20",max_length=500,null=True,blank=True)
    ans20 = models.BooleanField(verbose_name="Option 20 value", default=False)
    first_activation_time = models.DateTimeField(verbose_name="Activation time", null=True)

class StudentAnswers(models.Model):
    rollno =  models.CharField(max_length=10)
    q = models.IntegerField(verbose_name="Question number",    default=0    )
    answer_time = models.DateTimeField(null=True)
    is_correct = models.BooleanField(verbose_name="Answer status", default=False)
    user_agent = models.CharField(verbose_name='Device Used',  max_length=100,null=True )
    op1 = models.IntegerField(verbose_name="Option number 1",    default=0    )
    op2 = models.IntegerField(verbose_name="Option number 2",    default=0    )
    op3 = models.IntegerField(verbose_name="Option number 3",    default=0    )
    op4 = models.IntegerField(verbose_name="Option number 4",    default=0    )
    ans1 = models.BooleanField(verbose_name="Answer given 1", default=False)
    ans2 = models.BooleanField(verbose_name="Answer given 2", default=False)
    ans3 = models.BooleanField(verbose_name="Answer given 3", default=False)
    ans4 = models.BooleanField(verbose_name="Answer given 4", default=False)

class SystemState(models.Model):
    SYS_MODE = ( ( 'QUIZ', 'Quiz is running'), ('INACTIVE','Inactive') )
    activeq = models.IntegerField(verbose_name="Question number", default=0    )
    num_answered = models.IntegerField(verbose_name="Number of students answered", default=0)
    num_attendance = models.IntegerField(verbose_name="Number of attendance", default=0)
    mode = models.CharField(verbose_name='Mode', choices=SYS_MODE, default='INACTIVE', max_length=20 )
